### ISSUE TITLE
change default output directory

### ISSUE THREAD

**Issue by blshkv** [OWASP/Amass#143]
the current default output directory is:
``` '$CMD'/amass_output```

this is actually not common and will pollute user's filesystem. Please consider changing it to:
``` ~/.amass/```

btw, there is no real point adding ```_output``` ```_config.conf``` or ```_setttings.ini```. This is given.

It would be also good to have a default config location (--config default value), something like:
/etc/amass.conf

**Comment by caffix** [comment]
Naming the directory '/.amass/' is not an option since Snap does not allow hidden files to be created with the isolated environment.

We can look into some changes to the filenames.

We could provide a default configuration file location, but please keep in mind that Amass is not only for *nix environments

**Comment by blshkv** [comment]
sorry for mixing two different issues (default dir and config default values).
The main point of this issue is not to create the output directory in the ```current``` directory.

I'm not sure what it has to do with Snap. The tool should be creating this directory after the installation, during a regular user's run, in his home directory. I googled for a cross platform library quickly and found:
https://github.com/mitchellh/go-homedir

**Comment by caffix** [comment]
Thank you for the clarification. We should be able to implement most of the changes you're suggesting

**Comment by blshkv** [comment]
Thank you
