### ISSUE TITLE
Where to put amass_config.ini ?

### ISSUE THREAD

**Issue by SoufianeAbbad** [OWASP/Amass#153]
I downloaded the precompiled version of Amass for Windows but I don't where to put amass_config.ini.
Do I really need that file to make Amass get me more subdomains?

**Comment by caffix** [comment]
You do not need the configuration file to use Amass unless you're providing API keys or changing some of the more advanced settings. The file can be located wherever you wish, and the path is provided to the '-config' flag.

In the future, please bring questions like these to our chat, since this is not an issue with the project
