### ISSUE TITLE
Amass is not enumerating multible domains

### ISSUE THREAD

**Issue by maria-3li** [OWASP/Amass#312]
I have used amass in a script to enumerate more than one domain by using another tool for threading, the scripts works fine, but Amass's output is not accurate. For example, I know that a specific domain have more than 50 subdomains, but amass only enumerated one subdomain when its used with multi-threading script. Is there any limitation regarding running more than one thread in the same time? 

PS: for the threading I used Interlace tool.

**Comment by fork-while-fork** [comment]
Use `-df` to run multiple domains at the same time with amass. Amass has concurrency built in so you don't need to run it with a wrapper that adds more threading. Because amass leverages a local data store, you are likely running into an issue where multiple instances of amass are fighting over the same database. There are workarounds if you must run multiple instances at once, but they are not recommended for many reasons (rate-limiting from data sources being the most significant).

**Comment by attacker007** [comment]
Hi @caffix 

It will be good if amass allow user to customize number of threads according to his requirements.

**Comment by electroxero** [comment]
Any update on this?

**Comment by moashxer** [comment]
so I started amass running in BG and used few custom scripts and tools like subfinder/assetfinder and all of those has been completed in few hours but amass still running, I appreciate that Amass have found few unique domains however in count wise of domain it's very low, and enumerating domains is slower compared to other tools
below is the command I ran;
amass enum -d domain.com -r 8.8.8.8 -o amass-enum.txt
In 24Hrs 
other tools 4K < amass 300 

I assume making concurrent request will fix the problem
