### ISSUE TITLE
Additional DNS Record Types & Zone Transfer Successful Tool Output

### ISSUE THREAD

**Issue by Outrun207** [OWASP/Amass#383]
It would be handy if Amass could collect and display other DNS record types (for example, txt records for found hostnames in zone transfers). 

Additionally, if a successful zone transfer is performed, I'd like Amass to alert me to this in it's tool output. An example may read: 

+Zone Transfer Successful for <domain> via <ns>.

**Comment by caffix** [comment]
Amass does query for TXT records, and when it discovers them, investigates the records for domain names and IP addresses. The same could be performed on other record types. I do not like the idea of printing the record data, since it would be very messy and output information that isn't relevant to the enumeration. On the other hand, printing the discovery of successful zone transfers is definitely a good idea!

**Comment by Outrun207** [comment]
Cool! Thanks, it'd be great to know if a zone transfer succeeds. LOVE AMASS! Thanks for your work. 

I guess I could maybe write it and submit a pull request?

**Comment by caffix** [comment]
Sounds great!
