### ISSUE TITLE
Same result in brute-force with wordlist: single VS multiple small splitted ones

### ISSUE THREAD

**Issue by nyrbte** [OWASP/Amass#434]
Hi guys, your tool is awesome, I usually recommend it when it can resolve some mate tasks related to pentest recon process.

I am curious about whether **I can split a big wordlist in small ones and run all them in parallel without losing results?** because some kind of combo operators between multiple words or something similar.

Single example:

```
amass enum -brute -w amass_subdomains.txt -norecursive -noalts -nolocaldb -d $target -o amass_scan_$target.txt
```

Multiple example with more than 1 wordlists running at the same time with small words count (wc -l):
```
amass enum -brute -w amass_subdomains_small_01.txt -norecursive -noalts -nolocaldb -d $target -o amass_scan_$targets_mall_01.txt
amass enum -brute -w amass_subdomains_small_02.txt -norecursive -noalts -nolocaldb -d $target -o amass_scan_$targets_mall_02.txt
...
```

**Comment by caffix** [comment]
This is a good question for the Discord server. I would not recommend breaking up your task, unless they are being run sequentially and using the graph database, since the results produced by Amass are impacted by previously discovered names and addresses. You are likely to obtain more findings when the task is executed as one instantiation
