### ISSUE TITLE
altdns-like permutations 

### ISSUE THREAD

**Issue by michenriksen** [OWASP/Amass#55]
I recently discovered the [altdns](https://github.com/infosec-au/altdns) tool which takes a list of domains and permutates them by appending and prepending various [common words](https://github.com/infosec-au/altdns/blob/master/words.txt) to subdomains. I think this would be a cool addition to Amass' existing alteration engine.

I will happily work on a PR for this, I just wanted to make sure you think it would be a good addition to Amass before starting work on it. :)

Thanks for a great tool! 👍

**Comment by madaratech** [comment]
Just to mention we have improved version of `altdns` in GO version [goaltdns](https://github.com/subfinder/goaltdns) as well.

**Comment by caffix** [comment]
@michenriksen I originally took out the appending and prepending features of alternative names due to the extra resolution it added without many returns. That said, I am definitely interested in seeing your PR and am happy to reintroduce those features if you feel there is value to be gained. Thanks!

**Comment by caffix** [comment]
@michenriksen Are you still planning to contribute to the alterations service? I was looking forward to seeing the ideas you had in mind.

**Comment by caffix** [comment]
The names alteration services seem to be doing well now
