### ISSUE TITLE
Alterations   don't  have  wildcard domain check

### ISSUE THREAD

**Issue by icezhaoL** [OWASP/Amass#600]
If there is a wildcard domian from passive source.
Alterations   will be have more invaild result

**Comment by caffix** [comment]
Names generated by alterations and brute-forcing must be resolved by DNS and checked by wildcard detection just like all other domain names. If you're experiencing a problem with wildcard detection, it's more likely due to setting your own DNS resolvers. Please bring these types of concerns to our Discord server. Thank you

**Comment by JensTimmerman** [comment]
I'm having the same issue,
a domain which has a wildcard dns configured just seems to keep on showing matches for alterations...
